version: '3'

services:
  node1:
    build: ./app
    ports:
    - "8081:8080"
    environment:
    - NODE=1
  node2:
    build: ./app
    ports:
    - "8082:8080"
    environment:
    - NODE=2
  nginx:
    build: ./nginx 
    ports:
    - "8080:80"
    depends_on:
      - node1
      - node2
